// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/whoami.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Returns the signed-in TeamFokus user's profile, role and company/team assignment.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const uid = ctx.getUserId();
    const sb = supabaseForUser(ctx);
    const [{ data: profile }, { data: roles }, { data: membership }, { data: teams }] = await Promise.all([
      sb.from("profiles").select("id, display_name, onboarded, beta_access").eq("id", uid).maybeSingle(),
      sb.from("user_roles").select("role, company_id").eq("user_id", uid),
      sb.from("company_members").select("company_id").eq("user_id", uid),
      sb.from("team_members").select("team_id").eq("user_id", uid)
    ]);
    const result = {
      user_id: uid,
      email: ctx.getUserEmail(),
      profile,
      roles: roles ?? [],
      companies: (membership ?? []).map((m) => m.company_id),
      teams: (teams ?? []).map((t) => t.team_id)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-my-teams.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_teams_default = defineTool2({
  name: "list_my_teams",
  title: "List my teams",
  description: "Lists the TeamFokus teams the signed-in user belongs to (RLS-scoped).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    const { data: memberships, error: mErr } = await sb.from("team_members").select("team_id").eq("user_id", ctx.getUserId());
    if (mErr) return { content: [{ type: "text", text: mErr.message }], isError: true };
    const ids = (memberships ?? []).map((m) => m.team_id);
    if (ids.length === 0) {
      return { content: [{ type: "text", text: "No team memberships." }], structuredContent: { teams: [] } };
    }
    const { data: teams, error } = await sb.from("teams").select("*").in("id", ids);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(teams, null, 2) }],
      structuredContent: { teams: teams ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-notifications.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_notifications_default = defineTool3({
  name: "list_my_notifications",
  title: "List my notifications",
  description: "Lists the signed-in user's recent TeamFokus notifications.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("How many notifications to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    const { data, error } = await sb.from("notifications").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { notifications: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wbytrpxyhmzdowkiqqiw";
var mcp_default = defineMcp({
  name: "teamfokus-mcp",
  title: "TeamFokus",
  version: "0.1.0",
  instructions: "TeamFokus tools for the signed-in user. Use `whoami` to inspect the current account, `list_my_teams` for team memberships, and `list_my_notifications` for recent notifications. All tools respect the app's row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_my_teams_default, list_notifications_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
